
# Server Port
server.port: 7700

# Logger
logging.level:
  web: DEBUG
  '[com.simplilearn.spring]': DEBUG
  
# Server Name
spring.application.name: admin-server

# Enable Actuator
management.endpoints.web.exposure.include: "*"

# Eureka Server URL
eureka.client:
  serviceUrl:
    defaultZone: http://localhost:8761/eureka/